### ISSUE TITLE
cannot validate level 2 example

### ISSUE THREAD

**Issue by ghost** [5Tsrl/netex-italian-profile#1]
Hi,

I've tried to validate the examples against the XSD files.

There are the files I have just downloaded from your repo:

% md5 *                                                                          
MD5 (NeTEx_publication_EPIP.xsd) = bcf44b9834249bf3eeed4fbfa8d80796
MD5 (NeTEx_publication_Lev2.xsd) = 9ca9a8cac08f7ae897534f9b35e1472c
MD5 (Netex_ITA_1.10_EPIP+Level2.xml) = 2280b8661a8e446f1a186ece8684791d
MD5 (Netex_ITA_1.10_EPIP.xml) = 028678f2e5835a479b3a8b30ee12b36c
MD5 (_content_NeTEx_EPIP.xsd) = 84cc882c65def51f8641d54e2d2079a5
MD5 (_content_NeTEx_Lev2_ext.xsd) = 80147c7e6318360763ae23301ee58b1f
MD5 (gml_combo_v3_2_1_simplified.xsd) = 19084981069a104e4dfdd0806bdca6e0

I can validate Netex_ITA_1.10_EPIP.xml against NeTEx_publication_EPIP.xsd just fine.

However, if I try to validate Netex_ITA_1.10_EPIP+Level2.xml against NeTEx_publication_Lev2.xsd, I get errors.

xmllint (using libxml version 20914):

```
% xmllint -schema NeTEx_publication_Lev2.xsd -noout Netex_ITA_1.10_EPIP+Level2.xml     
Netex_ITA_1.10_EPIP+Level2.xml:121: element OrganisationRef: Schemas validity error : Element '{http://www.netex.org.uk/netex}OrganisationRef', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The type definition '{http://www.netex.org.uk/netex}OperatorRefStructure', specified by xsi:type, is blocked or not validly derived from the type definition of the element declaration.
Netex_ITA_1.10_EPIP+Level2.xml:951: element PassengerCapacity: Schemas validity error : Element '{http://www.netex.org.uk/netex}PassengerCapacity': This element is not expected.
Netex_ITA_1.10_EPIP+Level2.xml:10463: element PrivateCode: Schemas validity error : Element '{http://www.netex.org.uk/netex}PrivateCode': This element is not expected. Expected is one of ( {http://www.netex.org.uk/netex}vias, {http://www.netex.org.uk/netex}variants ).
Netex_ITA_1.10_EPIP+Level2.xml fails to validate
```

or xerces-j (2.12.2):

```
% xerces.sh NeTEx_publication_Lev2.xsd Netex_ITA_1.10_EPIP+Level2.xml              
[Error] Netex_ITA_1.10_EPIP+Level2.xml:121:105: cvc-elt.4.3: Type 'OperatorRefStructure' is not validly derived from the type definition, 'OrganisationRefStructure', of element 'OrganisationRef'.
[Error] Netex_ITA_1.10_EPIP+Level2.xml:951:64: cvc-complex-type.2.4.d: Invalid content was found starting with element 'PassengerCapacity'. No child element is expected at this point.
[Error] Netex_ITA_1.10_EPIP+Level2.xml:10463:21: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.netex.org.uk/netex":PrivateCode}'. One of '{"http://www.netex.org.uk/netex":vias, "http://www.netex.org.uk/netex":variants}' is expected.
Netex_ITA_1.10_EPIP+Level2.xml: 1451 ms
```

Could you please verify the level 2 example?

In case you can validate it as is, what validator(s) are you using?

Thanks,
Chris

**Comment by fabiogdb** [comment]
we forgot to modify the example: done now. Thank you for the warning
